init:
    python3 -m venv venv
    . venv/bin/activate && pip install -r requirements.txt
    cd ./../frontend/comp-remote/ && npm install && npm run build
run:
    . venv/bin/activate && flask --app backend run -p 3334