run:
    sudo apt install python3.12-venv
    python3 -m venv venv
    . venv/bin/activate && pip install Flask flask_cors websockets pynput && flask --app backend run -p 3334
reciever:
    sudo apt install python3.12-venv
    python3 -m venv venv
    . venv/bin/activate && pip install websockets pynput && python reciever.py